### ISSUE TITLE
Implement tests for ProvStore GET /store/api/v0/documents/:id(/flattened)(/view/:view)

### ISSUE THREAD

**Issue by mikej888** [prov-suite/service-tests#1]
I could not get REST invocations to work for:
- GET /store/api/v0/documents/:id(/flattened)
- GET /store/api/v0/documents/:id(/flattened)(/view/:view)

**Comment by trungdong** [comment]
Hi @mikej888,

Could you give more information about the issues you got when trying the above requests?
They are still working at my end with the following examples:

``` bash
curl -L "https://provenance.ecs.soton.ac.uk/store/api/v0/documents/147/" \
    -H "Accept: text/provenance-notation"

curl -L "https://provenance.ecs.soton.ac.uk/store/api/v0/documents/147/flattened/" \
    -H "Accept: text/provenance-notation"

curl -L "https://provenance.ecs.soton.ac.uk/store/api/v0/documents/147/flattened/views/data" \
    -H "Accept: text/provenance-notation"
```

**Comment by mikej888** [comment]
Hi @trungdong,

Problem solved, thanks to seeing these! I wasn't setting the Accept type. I've added tests for these now: a832e1d74d3652e0e21be4e9d933975760a7cfac!
